export enum CodeErrors {
  FAIL_TO_CREATE_BARBECUE = 'FAIL_TO_CREATE_BARBECUE',
  FAIL_TO_GET_ALL_BARBECUES = 'FAIL_TO_GET_ALL_BARBECUES',
  FAIL_TO_GET_BARBECUE = 'FAIL_TO_GET_BARBECUE',
  FAIL_TO_GET_BARBECUE_PARTICIPANTS = 'FAIL_TO_GET_BARBECUE_PARTICIPANTS',
  FAIL_TO_GET_PARTICIPANTS = 'FAIL_TO_GET_PARTICIPANTS',
  FAIL_TO_CREATE_PARTICIPANT = 'FAIL_TO_CREATE_PARTICIPANT',
}
