export enum CodeErrors {
  FAIL_TO_CREATE_BARBECUE = 'FAIL_TO_CREATE_BARBECUE',
  FAIL_TO_GET_ALL_BARBECUES = 'FAIL_TO_GET_ALL_BARBECUES',
  FAIL_TO_GET_BARBECUE = 'FAIL_TO_GET_BARBECUE',
  FAIL_TO_GET_BARBECUE_PARTICIPANTS = 'FAIL_TO_GET_BARBECUE_PARTICIPANTS',
  FAIL_TO_GET_PARTICIPANTS = 'FAIL_TO_GET_PARTICIPANTS',
  FAIL_TO_CREATE_PARTICIPANT = 'FAIL_TO_CREATE_PARTICIPANT',
  FAIL_TO_FIND_USER = 'FAIL_TO_FIND_USER',
  FAIL_TO_UPDATE_PARTICIPANTS = 'FAIL_TO_UPDATE_PARTICIPANTS',
  BARBECUE_NOT_FOUND = 'BARBECUE_NOT_FOUND',
  FAIL_TO_CREATE_USER = 'FAIL_TO_CREATE_USER',
  FAIL_TO_UPDATE_BARBECUE = 'FAIL_TO_UPDATE_BARBECUE',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
}
